In [2]:
import numpy as np
import csv

Reading data from csv

In [5]:
arr = []
with open('task.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
        arr.append(row)
print(arr)

[['min', '1', '4', '1'], ['6', '2', '=', '5'], ['8', '6', '>=', '7'], ['2', '4', '<=', '3'], ['1', '2', '>=', '0']]


Data preprocession 

Input must consist of 0 in empty spots

In [133]:
matrix = []
temp = []
n=0
if arr[0][0] == "min":
    temp.append(int(arr[0][1]) * -1)
    for i in range(2,len(arr[0])):
        temp.append(int(arr[0][i]))
        n+=1
else:
    temp.append(int(arr[0][1]))
    for i in range(2,len(arr[0])):
        temp.append(int(arr[0][i])*-1)
        n+=1
matrix.append(temp)
matrix = np.array(matrix)
temp = []
for i in range(1,len(arr)-1):
    temp2 = []
    for j in range(len(arr[i])):
        if (arr[i][j] != "<=") and (arr[i][j] != ">=") and (arr[i][j]!="="):
            temp2.append(int(arr[i][j]))
    temp.append(temp2)
temp = np.array(temp)

for i in range(len(temp)):    
    matrix = np.vstack((matrix, temp[i]))

#checking bi to be > 0
for i in range(1, len(temp)):
    if matrix[i][-1]<0:
        for j in range(len[i]):
            matrix[i][j] *= -1
#todo: add cases when x<=0 to the last string

for i in range(1,len(arr)-1):
    for j in range(len(arr[i])):
        if (arr[i][j] == "<="):
            matrix = np.hstack((matrix, np.zeros((matrix.shape[0], 1), dtype=matrix.dtype)))
            matrix[i][-1]=1 
            matrix[1:,[-2, -1]] = matrix[1:,[-1, -2]]
        elif (arr[i][j] == ">="):
            matrix = np.hstack((matrix, np.zeros((matrix.shape[0], 1), dtype=matrix.dtype)))
            matrix[i][-1]=-1
            matrix[1:,[-2, -1]] = matrix[1:,[-1, -2]]

for i in range(n):
    matrix = np.hstack((matrix, np.zeros((matrix.shape[0], 1), dtype=matrix.dtype)))
    matrix[i+1][-1]=1
    matrix[1:,[-2, -1]] = matrix[1:,[-1, -2]]

R = np.zeros(len(matrix[0]))

for i in range(1,n+1):
    R -= np.append(matrix[i][:-n-1],(np.append(np.zeros(n, dtype=matrix.dtype), matrix[i][-1])))
matrix = matrix.astype('float64')

R = np.array([R])
first_row = matrix[0]
z = first_row[0]
first_row[0] = 0
first_row = np.roll(first_row, -1)

matrix = np.delete(matrix, 0, 0)
matrix = np.vstack((first_row, matrix))

for i in range(len(matrix)):    
    R = np.vstack((R, np.array([matrix[i]])))  
matrix = R
print(matrix)

[[-14.  -8.   1.   0.   0.   0. -12.]
 [  4.   1.   0.   0.   0.   0.   0.]
 [  6.   2.   0.   0.   1.   0.   5.]
 [  8.   6.  -1.   0.   0.   1.   7.]
 [  2.   4.   0.   1.   0.   0.   3.]]


In [135]:
smallest_r = min (matrix[0][:-1])
print(smallest_r)
while smallest_r < 0:
    

-14.0
